In [1]:
# 1.	WAP find the average of given list of elements representing a grade of student.grades = [84, 84, 93, 78, 86, 73]
# Note: Please don’t use sum() function to add the elements from a list
grades = [84, 84, 93, 78, 86, 73]
total = 0
for i in range(len(grades)):
    total = total + grades[i]
print(total)
print(total/len(grades))

498
83.0


In [9]:
# 2.	WAP combine all the first characters from given list representing a some of the compelling qualities of a great leader.   
qualities = ['Passion', 'Yearning', 'Transparency', 'Humble', 'open-minded', 'Noble']   
combo = ""
for i in qualities:
    letter = i
    combo = combo + letter[0]
print(combo)


PYTHoN


In [5]:
# Write a program create 3x3 matrix using python. Take all the elements from the user. And also print the sum of diagonal elements from created matrix. 
import numpy as np
A = np.zeros([3,3])
print(A)
for i in range(len(A)):
    for j in range(len(A)):
        A[i][j] = int(input("Enter value:"))
print(A)
print(np.diag(A),sum(np.diag(A)))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[1. 5. 9.] 15.0


In [16]:
# 4.	Given dictionary representing a student name as a key and corresponding value is a grade which he obtained in different subjects.  WAP update each dict value with average score obtained by each student respectively. 
import numpy as np
scores = {
        'Student1': [65, 68, 59, 52, 69, 65, 55, 59], 
        'Student2': [60, 64, 60, 60, 88, 64, 68, 75],
        'Student3': [59, 72, 64, 62, 66, 68, 72, 73], 
        'Student4': [82, 62, 61, 54, 71, 89, 75, 73]
        }
avg_dict = {}
print(scores)
print(len(scores))
for k,v in scores.items():
    avg_dict[k] = np.mean(v)
    print(f"for {k} the average is {avg_dict[k]}")
print(avg_dict)

{'Student1': [65, 68, 59, 52, 69, 65, 55, 59], 'Student2': [60, 64, 60, 60, 88, 64, 68, 75], 'Student3': [59, 72, 64, 62, 66, 68, 72, 73], 'Student4': [82, 62, 61, 54, 71, 89, 75, 73]}
4
for Student1 the average is 61.5
for Student2 the average is 67.375
for Student3 the average is 67.0
for Student4 the average is 70.875
{'Student1': 61.5, 'Student2': 67.375, 'Student3': 67.0, 'Student4': 70.875}


In [25]:
# 5.	Write a program replace each string with an integer value in a given list of strings. The replacement integer value should be sum of ascci values of each character of the same string. 
holy_rivers =["Ganges", "Godavari", "Brahmaputra", "Narmada", "Yamuna", "Mahanadi", "Kaveri", "Tapti"]
# A(65) to Z (90)
# a(97) to z (122) 
ascii_sum = []
for i in holy_rivers:
    count = 0
    for j in i:
        count=count+ord(j)
    ascii_sum.append(count)
print(ascii_sum)
        


[597, 813, 1143, 692, 619, 787, 610, 514]


In [ ]:
# 6.	WAP print all duplicated values in descending order from the given input list. 
Input_list = [401, 403, 409, 403, 453, 402, 438, 401, 444]
duplicate = []
for i in Input_list:
    if Input_list.count(i)>1 and i not in duplicate:
        duplicate.append(i)
print(duplicate)


[401, 403]


In [ ]:
# 7.	Write a program find the maximum number from the given input list
Input_list = [99,82, 62, 61, 54, 71, 89, 75, 73]
max = 0
for i in range(len(Input_list)):
    for j in range(i+1, len(Input_list)):
        if (Input_list[i] > Input_list[j]) and (Input_list[i] > max):
            max = Input_list[i]
        elif (Input_list[i] < Input_list[j]) and (max < Input_list[j] ):
            max = Input_list[j]
        else:
            max = max
print(max)

99


In [44]:
# 8.	Write a program change the given input list by  doing rotate left.
A = [4, 5, 6, 7] 
print(A[1:4]+[A[0]])


[5, 6, 7, 4]


In [57]:
# 9.	Write a program take input strings of equal length and the length of strings should be greater than 5 and display the output by combining last three characters from the 1st string with first three characters from the second string. 
Input_Str1 = 'PYTHON'
Input_Str2 = 'PROGRAMMING'
print(Input_Str1[-3:])
print(Input_Str2[:3])
out_str = Input_Str1[-3:]+Input_Str2[:3]
print(out_str)



HON
PRO
HONPRO


In [61]:
# 10.	 Write a program join each and every character from the given string with hyphen(-)
Input_str = "PYTHON"
out_str = ''
for i in Input_str:
    out_str = out_str + (i + '-')
print(out_str)

P-Y-T-H-O-N-


In [72]:
# 11.	Write a program take 10 input strings of different lengths from the user and store all the strings into a list and display only odd length strings are the output in a list format.
List_details = []
for i in range(5):
    val = input("Enter string")
    List_details.append(val)
print(List_details)
list2 = []
for i in List_details:
    if len(i)%2 == 1:
        list2.append(i)
print(list2)
# 12.	Write a program find all even number from the given input list and display output as a list format. 
list3 = []
for i in List_details:
    if len(i)%2 == 0:
print(list3)

['chennai', 'banglore', 'puttur', 'tirupathi', 'puttur']
['chennai', 'tirupathi']
['banglore', 'puttur', 'puttur']


In [3]:
# 13. Given a string of even length and print the output as string contains last half added with first half of the given string
str1 = "python"
str2 = "encode"
print(str2[:3]+str1[-3:])

enchon


In [14]:
# 14.	WAP replace each string from the given list with the same string which is repeated with length of the string. 
Input = ['A', 'AB', 'ABC', 'ABCD']
output = []
for i in Input:
    output.append(i*len(i))
print(output)

['A', 'ABAB', 'ABCABCABC', 'ABCDABCDABCDABCD']


In [15]:
# 15.	Take two input strings from the user and concatenate two given strings by omitting the first character. 
str1 = "python"
str2 = "encode"
print(str1[1:]+str2[1:])

ythonncode


In [22]:
# 16.	Write a program find all even numbers from the given list.
Input_List = [18.8, 'Hyd', 18, 26.9, 19, 'BANG', 26, 33.7, 25, 'CHEN']
output_list = []
for i in Input_List:
    if type(i)== int and i%2 ==0:
        output_list.append(i)
print(output_list)

[18, 26]


In [32]:
# 17.	Write a program create a infinite loop, for each loop execution prompt the user input, If suppose user enters other than integer come out of the loop and display all user entered values as list. (use while loop to create infinite loop)
list1 = []
while True:
    val = input("enter integer")
    if val.isdigit():
        list1.append(int(val))
    else:
        break
print(list1)   

[1, 2, 3]


In [13]:
# 18.	Write a program create a random list of length 10 and print all the elements except the elements which are divisible by 4. 
import random

random_number = []
final_list = []
for _ in range(10):
    random_number.append(random.randint(1,100))
        
print(random_number)
for i in range(10):
    if random_number[i]%4==0:
        final_list.append(random_number[i])
print(f"random_number divisable by 4 {final_list}")

[99, 67, 1, 68, 2, 27, 2, 12, 98, 93]
random_number divisable by 4 [68, 12]


In [15]:
# 19.	Write a program convert the following list to a dictionary. 
X = [("A", 65), ("B", 66), ("C", 67), ("D", 68)]
dict1 = {}
for i in X:
    k = i[0]
    v = i[1]
    dict1[k]=v
print(dict1)


{'A': 65, 'B': 66, 'C': 67, 'D': 68}


In [19]:
# 20.	Write a program reverse each string from the given list and finally reverse a list. 
List1 = ['GANGA','YAMUNA']
list2 = []
# Step 1: reverse each string
for i in List1:
    list2.append(i[::-1])

# reverse the list
list2 = list2[::-1]
print(list2)

['ANUMAY', 'AGNAG']
